// This file exports all icons used in the app for easy management and consistency

import {
  // Navigation & UI
  HomeIcon,
  Bars3Icon,
  XMarkIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowPathIcon,
  MagnifyingGlassIcon,
  EllipsisVerticalIcon,
  EllipsisHorizontalIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  XCircleIcon,
  // User & Profile
  UserIcon,
  UserGroupIcon,
  UserPlusIcon,
  UserCircleIcon,
  // Communication
  ChatBubbleLeftIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftIcon,
  EnvelopeIcon,
  BellIcon,
  BellAlertIcon,
  MegaphoneIcon,
  // Actions
  PaperAirplaneIcon,
  PencilIcon,
  PencilSquareIcon,
  TrashIcon,
  DocumentDuplicateIcon,
  ClipboardIcon,
  ClipboardDocumentIcon,
  ShareIcon,
  LinkIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  // Media & Files
  PhotoIcon,
  CameraIcon,
  DocumentIcon,
  DocumentTextIcon,
  FolderIcon,
  FolderOpenIcon,
  PaperClipIcon,
  // Status & Feedback
  CheckCircleIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  QuestionMarkCircleIcon,
  // Settings & Controls
  Cog6ToothIcon,
  Cog8ToothIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  // Security
  LockClosedIcon,
  LockOpenIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  EyeIcon,
  EyeSlashIcon,
  KeyIcon,
  // Data & Analytics
  ChartBarIcon,
  ChartPieIcon,
  PresentationChartLineIcon,
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  // Time & Calendar
  ClockIcon,
  CalendarIcon,
  CalendarDaysIcon,
  // Misc
  SparklesIcon,
  LightBulbIcon,
  StarIcon,
  HeartIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  FireIcon,
  BoltIcon,
  GlobeAltIcon,
  MapIcon,
  MapPinIcon,
  BookOpenIcon,
  AcademicCapIcon,
  TrophyIcon,
  GiftIcon,
  TagIcon,
  HashtagIcon,
  AtSymbolIcon,
  // Device & Tech
  ComputerDesktopIcon,
  DevicePhoneMobileIcon,
  WifiIcon,
  SignalIcon,
  CpuChipIcon,
  ServerIcon,
  CloudIcon,
  // Layout
  Squares2X2Icon,
  ViewColumnsIcon,
  ListBulletIcon,
  QueueListIcon,
  TableCellsIcon,
  // Arrows & Directions
  ArrowsPointingOutIcon,
  ArrowsPointingInIcon,
  ArrowUturnLeftIcon,
  ArrowTopRightOnSquareIcon,
} from "@heroicons/react/24/outline"

import {
  HomeIcon as HomeIconSolid,
  UserIcon as UserIconSolid,
  BellIcon as BellIconSolid,
  HeartIcon as HeartIconSolid,
  StarIcon as StarIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  XCircleIcon as XCircleIconSolid,
  ExclamationCircleIcon as ExclamationCircleIconSolid,
  ChatBubbleLeftIcon as ChatBubbleLeftIconSolid,
  SparklesIcon as SparklesIconSolid,
  LockClosedIcon as LockClosedIconSolid,
  ShieldCheckIcon as ShieldCheckIconSolid,
  HandThumbUpIcon as HandThumbUpIconSolid,
  FireIcon as FireIconSolid,
  BoltIcon as BoltIconSolid,
} from "@heroicons/react/24/solid"

// Mini icons for smaller UI elements
import {
  ChevronDownIcon as ChevronDownIconMini,
  ChevronUpIcon as ChevronUpIconMini,
  ChevronLeftIcon as ChevronLeftIconMini,
  ChevronRightIcon as ChevronRightIconMini,
  CheckIcon as CheckIconMini,
  XMarkIcon as XMarkIconMini,
  PlusIcon as PlusIconMini,
  MinusIcon as MinusIconMini,
} from "@heroicons/react/20/solid"

// Re-export all icons
export {
  // Outline icons
  HomeIcon,
  Bars3Icon,
  XMarkIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowPathIcon,
  MagnifyingGlassIcon,
  EllipsisVerticalIcon,
  EllipsisHorizontalIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  XCircleIcon,
  UserIcon,
  UserGroupIcon,
  UserPlusIcon,
  UserCircleIcon,
  ChatBubbleLeftIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftIcon,
  EnvelopeIcon,
  BellIcon,
  BellAlertIcon,
  MegaphoneIcon,
  PaperAirplaneIcon,
  PencilIcon,
  PencilSquareIcon,
  TrashIcon,
  DocumentDuplicateIcon,
  ClipboardIcon,
  ClipboardDocumentIcon,
  ShareIcon,
  LinkIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  PhotoIcon,
  CameraIcon,
  DocumentIcon,
  DocumentTextIcon,
  FolderIcon,
  FolderOpenIcon,
  PaperClipIcon,
  CheckCircleIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  QuestionMarkCircleIcon,
  Cog6ToothIcon,
  Cog8ToothIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  LockClosedIcon,
  LockOpenIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  EyeIcon,
  EyeSlashIcon,
  KeyIcon,
  ChartBarIcon,
  ChartPieIcon,
  PresentationChartLineIcon,
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  ClockIcon,
  CalendarIcon,
  CalendarDaysIcon,
  SparklesIcon,
  LightBulbIcon,
  StarIcon,
  HeartIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  FireIcon,
  BoltIcon,
  GlobeAltIcon,
  MapIcon,
  MapPinIcon,
  BookOpenIcon,
  AcademicCapIcon,
  TrophyIcon,
  GiftIcon,
  TagIcon,
  HashtagIcon,
  AtSymbolIcon,
  ComputerDesktopIcon,
  DevicePhoneMobileIcon,
  WifiIcon,
  SignalIcon,
  CpuChipIcon,
  ServerIcon,
  CloudIcon,
  Squares2X2Icon,
  ViewColumnsIcon,
  ListBulletIcon,
  QueueListIcon,
  TableCellsIcon,
  ArrowsPointingOutIcon,
  ArrowsPointingInIcon,
  ArrowUturnLeftIcon,
  ArrowTopRightOnSquareIcon,
  // Solid icons
  HomeIconSolid,
  UserIconSolid,
  BellIconSolid,
  HeartIconSolid,
  StarIconSolid,
  CheckCircleIconSolid,
  XCircleIconSolid,
  ExclamationCircleIconSolid,
  ChatBubbleLeftIconSolid,
  SparklesIconSolid,
  LockClosedIconSolid,
  ShieldCheckIconSolid,
  HandThumbUpIconSolid,
  FireIconSolid,
  BoltIconSolid,
  // Mini icons
  ChevronDownIconMini,
  ChevronUpIconMini,
  ChevronLeftIconMini,
  ChevronRightIconMini,
  CheckIconMini,
  XMarkIconMini,
  PlusIconMini,
  MinusIconMini,
}

// Icon mapping from Lucide to Heroicons for gradual migration
export const iconMap = {
  // Lucide name -> Heroicons component
  Home: HomeIcon,
  Menu: Bars3Icon,
  X: XMarkIcon,
  ChevronDown: ChevronDownIcon,
  ChevronUp: ChevronUpIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowRight: ArrowRightIcon,
  RefreshCw: ArrowPathIcon,
  Search: MagnifyingGlassIcon,
  MoreVertical: EllipsisVerticalIcon,
  MoreHorizontal: EllipsisHorizontalIcon,
  Plus: PlusIcon,
  Minus: MinusIcon,
  Check: CheckIcon,
  User: UserIcon,
  Users: UserGroupIcon,
  UserPlus: UserPlusIcon,
  MessageSquare: ChatBubbleLeftIcon,
  MessageCircle: ChatBubbleOvalLeftIcon,
  Mail: EnvelopeIcon,
  Bell: BellIcon,
  BellRing: BellAlertIcon,
  Send: PaperAirplaneIcon,
  Edit2: PencilIcon,
  Pencil: PencilSquareIcon,
  Trash2: TrashIcon,
  Copy: DocumentDuplicateIcon,
  Clipboard: ClipboardIcon,
  Share: ShareIcon,
  Link2: LinkIcon,
  Download: ArrowDownTrayIcon,
  Upload: ArrowUpTrayIcon,
  Image: PhotoIcon,
  Camera: CameraIcon,
  FileText: DocumentTextIcon,
  File: DocumentIcon,
  Folder: FolderIcon,
  FolderOpen: FolderOpenIcon,
  Paperclip: PaperClipIcon,
  CheckCircle: CheckCircleIcon,
  AlertCircle: ExclamationCircleIcon,
  AlertTriangle: ExclamationTriangleIcon,
  Info: InformationCircleIcon,
  HelpCircle: QuestionMarkCircleIcon,
  Settings: Cog6ToothIcon,
  Settings2: Cog8ToothIcon,
  Sliders: AdjustmentsHorizontalIcon,
  Lock: LockClosedIcon,
  Unlock: LockOpenIcon,
  Shield: ShieldCheckIcon,
  Eye: EyeIcon,
  EyeOff: EyeSlashIcon,
  Key: KeyIcon,
  BarChart3: ChartBarIcon,
  PieChart: ChartPieIcon,
  TrendingUp: ArrowTrendingUpIcon,
  TrendingDown: ArrowTrendingDownIcon,
  Clock: ClockIcon,
  Calendar: CalendarIcon,
  Sparkles: SparklesIcon,
  Lightbulb: LightBulbIcon,
  Star: StarIcon,
  Heart: HeartIcon,
  ThumbsUp: HandThumbUpIcon,
  ThumbsDown: HandThumbDownIcon,
  Flame: FireIcon,
  Zap: BoltIcon,
  Globe: GlobeAltIcon,
  Map: MapIcon,
  MapPin: MapPinIcon,
  BookOpen: BookOpenIcon,
  GraduationCap: AcademicCapIcon,
  Trophy: TrophyIcon,
  Gift: GiftIcon,
  Tag: TagIcon,
  Hash: HashtagIcon,
  AtSign: AtSymbolIcon,
  Monitor: ComputerDesktopIcon,
  Smartphone: DevicePhoneMobileIcon,
  Wifi: WifiIcon,
  Signal: SignalIcon,
  Cpu: CpuChipIcon,
  Server: ServerIcon,
  Cloud: CloudIcon,
  Grid: Squares2X2Icon,
  Columns: ViewColumnsIcon,
  List: ListBulletIcon,
  Table: TableCellsIcon,
  Maximize: ArrowsPointingOutIcon,
  Minimize: ArrowsPointingInIcon,
  Reply: ArrowUturnLeftIcon,
  ExternalLink: ArrowTopRightOnSquareIcon,
  Loader2: ArrowPathIcon,
  Brain: SparklesIcon,
  Activity: PresentationChartLineIcon,
  Target: MapPinIcon,
  Layers: Squares2X2Icon,
  GitBranch: ShareIcon,
  Crown: TrophyIcon,
  Pin: MapPinIcon,
  Beaker: SparklesIcon,
  Bot: CpuChipIcon,
  Palette: SparklesIcon,
  Sun: SparklesIcon,
  Moon: SparklesIcon,
  Volume2: BellIcon,
  CheckCheck: CheckCircleIcon,
  CheckCircle2: CheckCircleIcon,
  LogIn: ArrowRightIcon,
  Save: ArrowDownTrayIcon,
  Database: ServerIcon,
  WifiOff: XCircleIcon,
}

// Helper component for loading state
export function LoadingSpinner({ className = "h-5 w-5" }: { className?: string }) {
  return <ArrowPathIcon className={`${className} animate-spin`} />
}
